### ISSUE TITLE
Allow proxying responses when forwarding

### ISSUE THREAD

**Issue by nextrevision** [darklynx/request-baskets#24]
When setting a forward URL, have an additional setting that allows for the request to complete and pass the response back to the client. I have this minimally setup in my fork, but would probably need to do some work to make it scale.

If this is something you're interested in, I can polish up my fork and submit a PR.

**Comment by darklynx** [comment]
Thank you for the interest in request baskets.

I agree that feature you have describe is important when service is used in proxy mode, and passing back the meaningful response generated by back-end service is essential for some web hooks and notification services.

Such behavior, however, clashes with [response settings](https://rbaskets.in/api.html#tag/responses). That is why, I think, it should be reflected in basket setting as a `boolean` flag to enable/disable response forwarding.

I'm not sure about the implication on the request baskets service itself and its performance if underlying services will response slow, maybe setting up a reasonably short connect/read timeouts may prevent the DOS issues if basket with slow back-end is flooded with incoming requests.

I'll appreciate the PR. Thank you in advance!

**Comment by nextrevision** [comment]
Ok awesome, I'll work on getting a PR up.
