### ISSUE TITLE
Please add dockerhub build to this repo

### ISSUE THREAD

**Issue by everflux** [darklynx/request-baskets#34]
Please add dockerhub automated build to this repo, so the image is available without custom build

**Comment by darklynx** [comment]
@everflux I have improved the main Dockerfile to build container image using the multi-stage feature of Docker, and I configured an automated build on https://hub.docker.com, now you can simply use:
```
$ docker pull darklynx/request-baskets
```
to get the latest version of the service.

Thank you for your advice!

P.S. I'm planning to improve configuration possibilities of the created container in the future to allow passing the configuration parameters using environment variables.
