### ISSUE TITLE
add ability to get full raw GET parameters in the "GET" green header

### ISSUE THREAD

**Issue by homerograco** [darklynx/request-baskets#51]
Currently the green GET header displays a truncated GET request only. 

![image](https://user-images.githubusercontent.com/16291485/69226343-4768ee80-0b80-11ea-882e-6af08600acbb.png)

In some situations it is necessary to copy+paste the whole request, and currently this is only possible by manually copying the parsed parameters as seen in the "Query Params" box. 

A suggestion: why not make the GET header expandable, so that if the user clicks on it, it shows the complete GET request as received by the basket?

**Comment by luisfmelo** [comment]
What if we put a copy button? I can pick this issue.

**Comment by darklynx** [comment]
I was thinking to implement a copy button that copies the whole request details as JSON into clipboard including URL, headers, body, and not just the URL with GET parameters.

PRs are welcome, I will appreciate any help. Thanks.

**Comment by luisfmelo** [comment]
I was exploring around the code and I notice that the HTML is rendered inside a `go` file. What about using a template processing engine? 
Quick search and I got this one as an example: `github.com/thedevsaddam/renderer/`

**Comment by darklynx** [comment]
This will break the idea of `request-baskets` to be a self-contained executable file after compilation.

The template engine that you have mentioned above will require a folder with templates for processing on the disk. Which is nice during development and debugging of the UI, but will require to ship executable + folder with templates, which is against of my original idea.
