### ISSUE TITLE
Provide parameter to instantiate basket on startup

### ISSUE THREAD

**Issue by everflux** [darklynx/request-baskets#57]
Similar to provide a defined token it would be great if I could launch request-baskets as container and have a defined basket ready without manual intervention.

**Comment by darklynx** [comment]
sound like a nice feature, how do you think the configuration for basket or multiple baskets should be passed to the service?

as a link to a configuration file, as command line arguments? original project where I took the ideas for RequestBaskets from used a parameter that was pointing to yaml-file with configuration for baskets for that: https://github.com/kyledayton/requesthub#configuration

**Comment by everflux** [comment]
I think for a single basket an environment parameter would be sufficient (like for the token).
For more complex scenarios path to a configuration file sounds fine. For me the single basket case is especially interesting, since I can then create a docker-compose file for my app with a simulated webhook receiver that works out of the box.

**Comment by darklynx** [comment]
Every basket gets its token to access :) should it be randomly generated, set via another parameter, or master password is used? 🤔
I'm just trying to figure out how the configuration should look for command line parameters and what are the drawbacks of the simplification.

E.g. new parameter: `-baskets abc,klm,xyz` - creates initial baskets (if they do not already exist) and assigns random token to every basket, tokens are logged into a console output (like generated master token), but you do not need them if you have predefined a master token from outside.

**Comment by everflux** [comment]
I think there are quite different use cases. One is to provide request-baskets as a central instance for multiple users. Therefore multiple baskets and tokens are needed.
The other one is to have an easy to setup ("one click") instance running with predetermined settings to be able to use it right away in a developer environment. That is my use case, therefore I need predetermined token and bucket, but I don't need multiple buckets or tokens.
The setting is a single docker-compose file where my app, database, request-baskets and mailcatcher are running to simulate the whole environment. (And beeing able to run the app against the container from my IDE as well). But it is quite inconvenient to first start request-baskets, then create a basket manually with a specific name (so I don't need reconfigure the application) in order to use it.
A single basket like the single master token would suffice :)

**Comment by anorm** [comment]
I second @everflux on this. This would be a very useful feature for having a basket instantly available for local development using docker-compose. A single basket would suffice for me as well, using the master token, but to cover other potential use cases as well, maybe allow either a `-basket` option to be specified multiple times or allow a `-baskets` option to accept an array of basket specifications.

A basket specification could for example be `name[@token]` meaning if you only specify a name, a random token will be created for it but if you add a token in the spec, it will be used.

**Example:**
```
$ request-baskets -basket my-basket@my-token -basket my-other-basket
...
2020/08/19 15:37:41 [info] creating basket: my-basket
2020/08/19 15:37:41 [info] creating basket: my-other-basket
2020/08/19 15:37:41 [info] generated token for my-other-basket: 0uGFvGq6aj_0PqnPrgk3iCGo4pF6JtoXMCcAP0iUbe1L
...
```

Here, two baskets will be created. The first one `my-basket` with the token `my-token` and the second one `my-other-basket` with a randomly generated token.

Because the token can contain a large variety of characters, specifying multiple baskets using repeated `-basket` arguments is probably better than joining basket specifications using `,`.

**Comment by darklynx** [comment]
@everflux @anorm 
```
$ ./request-baskets -basket abc -basket xyz -basket abc/xyz -basket abc
2020/08/26 00:19:25 [info] generated master token: qr-uUdCQpjjIBeE6wquXTEzh5pGvFo0NO2ibP06vcBlE
2020/08/26 00:19:25 [info] service version: v1.1.0 from commit: a9d9214 (a9d92140c2a9e27d097f3fd38d9871022daee6c8)
2020/08/26 00:19:25 [info] using in-memory database to store baskets
2020/08/26 00:19:25 [info] basket 'abc' is auto-created with access token: dZCBn96hhh3LPyftLziG9QNYG8sr57D2LXsk2eVHMFDR
2020/08/26 00:19:25 [info] basket 'xyz' is auto-created with access token: OIUUIMiHQOGHwyzB7QJtJGBqQ-InRz_olOLQ_r6Wyxbc
2020/08/26 00:19:25 [error] invalid basket name to auto-create; 'abc/xyz' does not match pattern: ^[\w\d\-_\.]{1,250}$
2020/08/26 00:19:25 [error] Basket with name 'abc' already exists
2020/08/26 00:19:25 [info] HTTP server is listening on 127.0.0.1:55555

```

I decided to follow the advice of @anorm and implemented a support for multiple entries of parameter `-basket` to specify a basket name for auto-creation. I skipped the idea of predefined passwords for baskets as it would require more internal redesign of how baskets are currently created. But you can always predefine the master token using `-token` parameter and access any auto-created basket with that token.

**Comment by everflux** [comment]
Very nice!

**Comment by anorm** [comment]
Sweet ❤
