### ISSUE TITLE
Add 'copy to clipboard' button to UI

### ISSUE THREAD

**Issue by everflux** [darklynx/request-baskets#59]
After creating a new basket the URL of the basket is shown. Selecting the right text and copying it to the clipboard is a little fiddly. It would be a nice UX enhancement to provide a small copy-to-browser-clipboard icon that uses the html5 clipboard API: https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API
(Like the share-this-basket link on the upper right, but without the token and near to the URL.)

**Comment by darklynx** [comment]
done
