### ISSUE TITLE
Restrict creation of new baskets

### ISSUE THREAD

**Issue by fomojola** [darklynx/request-baskets#71]
Would it be possible to restrict creation of new baskets (and potentially restrict all access to the /api and /web paths) to clients that present the main token? This would potentially make it easier to host Request Baskets on public-facing servers. Right now anyone who visits the domain it is hosted on can immediately create an unlimited number of baskets.

**Comment by darklynx** [comment]
This make sense.

Although, I believe restricting the creation of new baskets to the main token owner is sufficient 🤔 Even if UI is accessible, visitors from outside wont be able to use or misuse the service.

**Comment by darklynx** [comment]
@fomojola I just managed to implement the feature you have requested, the code is already in `master` branch, the public docker image will follow shortly.

Sorry for quite a delay, I really got little time to run my hobby activities.

Thanks you for the interesting and useful feature request!

**Comment by fomojola** [comment]
Looks golden! Just deployed v1.2.0 and happiness ensued.

Thanks!
