### ISSUE TITLE
Bootstrap Upgrade/Dark Mode

### ISSUE THREAD

**Issue by SoCuul** [darklynx/request-baskets#80]
Hi!

Currently the site is running off Bootstrap 3. If the site is upgraded to Bootstrap 5+, dark mode could be easily added. In a recent bootstrap update, dark-versions of all the main components have been added, and can be toggled with an attribute on the body element.

I also want to thank you for making such an amazing project.

**Comment by SoCuul** [comment]
Though it looks like it may be a lot of work, as the layout classes and syntax have changed between versions.

**Comment by SoCuul** [comment]
In the meantime, I've created my own bootstrap css theme (modified from another theme), which themes all elements of the site in a beautiful fashion.
It also implements the `prefers-color-scheme` media tag, to only switch to the dark theme when the OS requests it.

If you would like to try it out, you can find it here: https://github.com/socuul/requestbaskets-dark-theme

Note: The placement of some items are slightly switched, because the theme was adapted from other public themes.

**Comment by darklynx** [comment]
Hi @SoCuul ,

I like the idea of having light/dark theme support.

It's a good idea to migrate to Bootstrap 5, and support for light/dark switch out of the box could be a good motivation to invest into migration :)

Your last message with a link to a theme, is this a Bootstrap 3 theme (looks like it from the comments in the header)?

**Comment by darklynx** [comment]
@SoCuul in scope of [recent release](https://github.com/darklynx/request-baskets/releases/tag/v1.2.2) I have introduced a new command line argument to support CSS themes selection for web UI. By default, the `standard` theme from Bootstrap is still in use.

But I have added an `adaptive` CSS theme as well that points to your excellent work on introducing the dark/adaptive theme for Request Baskets service. You can see it in action already on https://rbaskets.in 

I still want to try to migrate UI on Bootstrap 5+, but it may take some time.

**Comment by darklynx** [comment]
@SoCuul Thank you for your contribution! 🙏

**Comment by darklynx** [comment]
I had to do some quick patch to the theme, and created a fork for that: https://github.com/darklynx/requestbaskets-dark-theme

What has happened? The [jsDeliver](https://www.jsdelivr.com/) has regenerated minified version of `requestbaskets-dark-theme@09176b7/bootstrap.min.css` and SRI was not matching the security HASH anymore.

They even warn us about it in the content of minified file: https://cdn.jsdelivr.net/gh/socuul/requestbaskets-dark-theme@09176b7/bootstrap.min.css
> ...
> Do NOT use SRI with dynamically generated files! More information: https://www.jsdelivr.com/using-sri-with-dynamic-files
>

**Comment by SoCuul** [comment]
I actually have no idea. I haven't touched the theme since I posted my earlier comment.
I did make a mistake by not providing a static minified file for SRI, though, which I completely overlooked by accident.

**Comment by SoCuul** [comment]
I've added a note to my repository redirecting them to yours, and I have left mine in read-only mode.
Thanks for fixing it though!
